# Generated by Django 4.2.3 on 2023-07-31 22:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_alter_comentario_autor_alter_publicacion_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
